package jetbrains.mps.baseLanguage.string.format.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class ExpressionStringComponent_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getStringFormat_5898401181601750277(SNode thisNode) {
    return "%s";
  }
}
