package jetbrains.mps.baseLanguage.string.format.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class ExpressionStringComponent_BehaviorDescriptor extends PlainStringComponent_BehaviorDescriptor {
  public ExpressionStringComponent_BehaviorDescriptor() {
  }

  public String virtual_getStringFormat_5898401181601750277(SNode thisNode) {
    return ExpressionStringComponent_Behavior.virtual_getStringFormat_5898401181601750277(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.string.format.structure.ExpressionStringComponent";
  }
}
