package jetbrains.mps.baseLanguage.string.format.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class FormattedString_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String call_buildFormattedString_5898401181601722445(SNode thisNode) {
    StringBuilder builder = new StringBuilder();
    for (SNode component : ListSequence.fromList(SLinkOperations.getTargets(thisNode, "components", true))) {
      builder.append(PlainStringComponent_Behavior.call_getStringFormat_5898401181601750277(component));
    }
    return builder.toString();
  }
}
