package jetbrains.mps.baseLanguage.string.format.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class FormattedString_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public FormattedString_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.string.format.structure.FormattedString";
  }
}
