package jetbrains.mps.baseLanguage.string.format.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class PlainStringComponent_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PlainStringComponent_BehaviorDescriptor() {
  }

  public String virtual_getStringFormat_5898401181601750277(SNode thisNode) {
    return PlainStringComponent_Behavior.virtual_getStringFormat_5898401181601750277(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baseLanguage.string.format.structure.PlainStringComponent";
  }
}
