package jetbrains.mps.baseLanguage.string.format.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import jetbrains.mps.smodel.language.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class PlainStringComponent_Behavior {
  private static Class[] PARAMETERS_5898401181601750277 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static String virtual_getStringFormat_5898401181601750277(SNode thisNode) {
    if (SPropertyOperations.getString(thisNode, "value") == null) {
      return "";
    }
    return SPropertyOperations.getString(thisNode, "value");
  }

  public static String call_getStringFormat_5898401181601750277(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (String) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.baseLanguage.string.format.structure.PlainStringComponent"), "virtual_getStringFormat_5898401181601750277", PARAMETERS_5898401181601750277, new Object[]{});
  }

  public static String callSuper_getStringFormat_5898401181601750277(SNode thisNode, String callerConceptFqName) {
    return (String) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "jetbrains.mps.baseLanguage.string.format.structure.PlainStringComponent"), callerConceptFqName, "virtual_getStringFormat_5898401181601750277", PARAMETERS_5898401181601750277, new Object[]{});
  }
}
