package jetbrains.mps.baseLanguage.string.format.behavior;

/*Generated by MPS */


public enum TypeCategories {
  GENERAL("b", "h", "s"),
  CHARACTER("c"),
  INTEGRAL("d", "o", "x"),
  FLOATING_POINT("e", "f", "g", "a"),
  DATE_TIME("t");

  private String[] conversions;

  TypeCategories(String... conversions) {
    this.conversions = conversions;
  }
}
