package jetbrains.mps.baseLanguage.string.format.sandbox.sandbox;

/*Generated by MPS */


public class Test {
  public void method(String text) {
    String ww3 = String.format("World War %s", 2);
    int beginDate = 1939;
    int endDate = 1945;
    String formatted = String.format("I want say some words about %s it began at %s and ended at %s. And some text in the end: %s", ww3, beginDate, endDate, text);
    System.out.println(formatted);
  }

  public static void main(String[] args) {
    new Test().method("Some text!");
  }
}
