package jetbrains.mps.baseLanguage.string.format.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilders;
import jetbrains.mps.lang.dataFlow.DataFlowManager;

public class DFABuilders extends DataFlowBuilders {
  public void install(DataFlowManager manager) {
    manager.register("jetbrains.mps.baseLanguage.string.format.structure.ExpressionStringComponent", new ExpressionStringComponent_DataFlow());
    manager.register("jetbrains.mps.baseLanguage.string.format.structure.FormattedString", new FormattedString_DataFlow());
  }
}
