package jetbrains.mps.baseLanguage.string.format.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilder;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.lang.dataFlow.DataFlowBuilderContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class FormattedString_DataFlow extends DataFlowBuilder {
  public FormattedString_DataFlow() {
  }

  public void build(final IOperationContext operationContext, final DataFlowBuilderContext _context) {
    for (SNode component : ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "components", true))) {
      _context.getBuilder().build((SNode) component);
    }
  }
}
