package jetbrains.mps.baseLanguage.string.format.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.CellActionType;
import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.nodeEditor.cells.EditorCell_Label;

public class complete_ExpressionStringComponent {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.COMPLETE, new complete_ExpressionStringComponent.complete_ExpressionStringComponent_COMPLETE(node));
  }

  public static class complete_ExpressionStringComponent_COMPLETE extends EditorCellAction {
    /*package*/ SNode myNode;

    public complete_ExpressionStringComponent_COMPLETE(SNode node) {
      this.myNode = node;
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      EditorCell cell = editorContext.getContextCell();
      int caret = ((EditorCell_Label) cell).getCaretPosition();
    }
  }
}
